version: "3.7"

services:
  front:
    container_name: "front"
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    ports:
      - "80:80"
    volumes: 
      - "./docker/nginx:/var/log/nginx"
      - "./docker/front/nginx:/etc/nginx/conf.d/"
    depends_on:
      - back
  back:
    container_name: "back"
    build:
      context: ./
      dockerfile: ./docker/back/Dockerfile
    ports:
      - "8081:8081"
    depends_on: 
      - db
  db:
    image: mongo:latest
    container_name: db
    hostname: db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: test123
        MONGO_INITDB_DATABASE: countofmoney
    ports:
        - "27017:27017"